services:
  users:
    build: ./users
    container_name: users_service
    depends_on:
      - auth_db
      - auth-celery
      - rabbitmq
    ports:
      - "8000:8000"
    environment:
      DB_NAME: trello_auth
      DB_USER: postgres
      DB_PASSWORD: 12345
      DB_HOST: auth_db
      DB_PORT: 5432
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq-service:5672//
      CELERY_RESULT_BACKEND: redis://redis-service:6379/0
    volumes:
      - ./users:/app
  auth_db:
    image: postgres:16
    container_name: auth_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: trello_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
  redis:
    image: redis:7.4.7-alpine
    container_name: redis-service
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4.2.1-management
    container_name: rabbitmq-service
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest 
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  auth-celery:
    build: ./users
    container_name: auth-celery
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DB_NAME: trello_auth
      DB_USER: postgres
      DB_PASSWORD: 12345
      DB_HOST: auth_db
      DB_PORT: 5432
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq-service:5672//
      CELERY_RESULT_BACKEND: redis://redis-service:6379/0
    command: sh -c "celery -A users worker --loglevel=info"
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - auth_db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data: 